# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - run:
         name: Install PHP libzip-dev
         command: sudo apt-get install -y libzip-dev

      - run:
         name: Install PHP zip
         command: sudo docker-php-ext-install zip
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!i
      - run: vendor/bin/codecept build
      - run: vendor/bin/codecept run

  deployment:
    staging:
      commands:
        - |
          cat >~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_TOKEN
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_TOKEN
          EOF
        - chmod 600 ~/.netrc # Heroku cli complains about permissions without this
        - heroku maintenance:on --app mighty-mesa-44488
        - heroku scale worker=0 --app mighty-mesa-44488
        - git push git@heroku.com:mighty-mesa-44488.git $CIRCLE_SHA1:refs/heads/master
        - heroku scale worker=1 --app mighty-mesa-44488
        - heroku maintenance:off --app mighty-mesa-44488
